apps/diary/urls.py
from django.urls import path

from apps.diary.apps import DiaryConfig
from apps.diary.views import (
    HomeView,
    DiaryEntryListView,
    DiaryEntryDetailView,
    DiaryEntryCreateView,
    DiaryEntryDeleteView,
    DiaryEntryUpdateView,
)

app_name = DiaryConfig.name


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("diary/", DiaryEntryListView.as_view(), name="diary_entry_list"),
    path("diary/create/", DiaryEntryCreateView.as_view(), name="diary_entry_create"),
    path("diary/<int:pk>/", DiaryEntryDetailView.as_view(), name="diary_entry_detail"),
    path("diary/update/<int:pk>/", DiaryEntryUpdateView.as_view(), name="diary_entry_update"),
    path("diary/delete/<int:pk>/", DiaryEntryDeleteView.as_view(), name="diary_entry_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.diary.urls", namespace="diary")),
    path("users/", include("apps.users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/diary/models.py
from django.db import models

from apps.users.models import NULLABLE, Users


class DiaryEntry(models.Model):
    """Модель записи пользователя в его дневнике."""

    author = models.ForeignKey(Users, on_delete=models.CASCADE, **NULLABLE, verbose_name="Автор")

    title = models.CharField(max_length=255, verbose_name="Название записи")
    text = models.TextField(verbose_name="Текст записи")
    image = models.ImageField(
        upload_to="diary/diary_entry", default="diary/diary_entry/default.png", **NULLABLE, verbose_name="Изображение"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    is_published = models.BooleanField(default=True, verbose_name="Статус публикации")

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"
        ordering = ["author", "updated_at"]
        db_table = "_d_diary_entry"
        db_table_comment = "Записи в дневнике"

apps/diary/forms.py
from django.forms import ModelForm
from core.forms import StyleFormMixin
from apps.diary.models import DiaryEntry


class DiaryEntryForm(StyleFormMixin, ModelForm):

    class Meta:
        model = DiaryEntry
        fields = ("title", "text", "image", "is_published")

apps/diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from apps.diary.forms import DiaryEntryForm
from apps.diary.models import DiaryEntry


class HomeView(TemplateView):
    template_name = "diary/home.html"
    extra_context = {"title": "Главная страница"}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return context_data


class DiaryEntryListView(ListView):
    model = DiaryEntry
    template_name = "diary/diary_entry/diary_entry_list.html"
    extra_context = {"title": "Мой дневник"}

    def get_queryset(self):
        queryset = super().get_queryset()

        user = self.request.user
        if user.is_superuser:
            return queryset
        else:
            queryset = queryset.filter(author=self.request.user)

            query = self.request.GET.get("q")
            if query:
                queryset = queryset.filter(Q(title__icontains=query) | Q(text__icontains=query))
            return queryset


class DiaryEntryDetailView(DetailView):
    model = DiaryEntry
    template_name = "diary/diary_entry/diary_entry_detail.html"
    extra_context = {"title": "Моя запись"}

    def get_object(self, *args, **kwargs):
        object = super().get_object()
        user = self.request.user
        if user.is_superuser or object.author == user:
            return object
        else:
            raise PermissionDenied


class DiaryEntryCreateView(LoginRequiredMixin, CreateView):
    model = DiaryEntry
    form_class = DiaryEntryForm
    template_name = "diary/diary_entry/diary_entry_form.html"
    extra_context = {"title": "Создать запис"}
    login_url = reverse_lazy("users:login")

    def get_success_url(self):
        return reverse("diary:diary_entry_detail", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class DiaryEntryUpdateView(LoginRequiredMixin, UpdateView):
    model = DiaryEntry
    form_class = DiaryEntryForm
    template_name = "diary/diary_entry/diary_entry_form.html"
    extra_context = {"title": "Редактировать запись"}
    login_url = reverse_lazy("users:login")

    def get_success_url(self):
        return reverse("diary:diary_entry_detail", kwargs={"pk": self.object.pk})

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or object.author == user:
            return object
        else:
            raise PermissionDenied


class DiaryEntryDeleteView(LoginRequiredMixin, DeleteView):
    model = DiaryEntry
    template_name = "diary/diary_entry/diary_entry_form.html"
    extra_context = {"title": "Удаление статьи"}
    success_url = reverse_lazy("diary:diary_entry_list")
    login_url = reverse_lazy("users:login")

    def get_object(self, *args, **kwargs):
        object = super().get_object()
        user = self.request.user
        if user.is_superuser or object.author == user:
            return object
        else:
            raise PermissionDenied

apps/diary/templates/diary/diary_entry/diary_entry_confirm_delete.html
{% extends 'diary/base.html' %} {% block content %} {% load my_tags %}

<div class="container">
  <div class="row">
    <div class="col-xxl-3"></div>
    <div class="col-xxl-6 text-center justify-content-center">
      <form method="post" enctype="multipart/form-data" class="mb-4">
        {% csrf_token %}
        <p>Желаете удалить эту статью?</p>
        <button type="submit" class="btn btn-danger">Подтвердить</button>
        <a href="{% url 'diary:diary_entry_detail' object.pk %}" class="btn btn-warning">Отмена</a>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

apps/diary/templates/diary/diary_entry/diary_entry_detail.html
{% extends 'diary/base.html' %} {% block content %} {% load my_tags %}

<div class="btn-group text-right" role="group" aria-label="Basic outlined button group">
  <button type="button" class="btn btn-outline-primary">
    <a href="{% url 'diary:diary_entry_update' object.pk %}">Отредактировать</a>
  </button>

  <button type="button" class="btn btn-outline-primary">
    <a href="{% url 'diary:diary_entry_delete' object.pk %}">Удалить</a>
  </button>
</div>

<div class="text-center">
  <h3>{{ object.title }}</h3>
</div>

<div class="clearfix">
  <div class="row">
    <div class="col-4">
      <div class="float-left mr-3 mb-3">
        {% if object.image %}
        <img src="{{ object.image|media_url }}" class="img-fluid" alt="Responsive image" width="130%" />
        {% else %}
        <p>Изображения нет.</p>
        {% endif %} {% if user.is_superuser %}
        <small class="text-muted">
          Автор: {{ object.author.first_name }} {{ object.author.last_name }} {{object.author.middle_name }} </small
        ><br />
        {% endif %}
        <small class="text-muted">Создано: {{ object.created_at }}</small><br />
        <small class="text-muted">В редакции от: {{ object.created_at }}</small>
      </div>
    </div>
    <div class="col-8">
      <div class="lh-lg fs-5">{{ object.text }}</div>
    </div>
  </div>
</div>

{% endblock content %}

apps/diary/templates/diary/diary_entry/diary_entry_form.html
{% extends 'diary/base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-xxl-3"></div>
    <div class="col-xxl-5">
      <p class="fs-4 text-center">{% if object %}Редактирование{% else %}Создание{% endif %} статьи</p>

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <button class="btn-outline-primary" type="submit">
          {% if object %} Изменить или Удалить {% else %} Добавить {% endif %}
        </button>
        {% if object %}
        <button
          class="btn-outline-primary"
          type="button"
          onclick="window.location.href='{% url 'diary:diary_entry_detail' object.pk %}'"
        >
          Отмена
        </button>
        {% else %}
        <button
          class="btn-outline-primary"
          type="button"
          onclick="window.location.href='{% url 'diary:diary_entry_list' %}'"
        >
          Отмена
        </button>
        {% endif %}
      </form>
    </div>
    <div class="col-xxl-4"></div>
  </div>
</div>

{% endblock content %}

apps/diary/templates/diary/diary_entry/diary_entry_list.html
{% extends 'diary/base.html' %} {% block content %} {% load my_tags %}
<div class="container">
  <div class="row mb-4">
    <div class="col-md-6">
      <form method="GET" action="{% url 'diary:diary_entry_list' %}">
        <div class="input-group">
          <input
            type="text"
            name="q"
            class="form-control"
            placeholder="Поиск по записям..."
            value="{{ request.GET.q }}"
          />
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">Поиск</button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-6 text-right">
      <button type="button" class="btn btn-outline-primary shadow-sm">
        <a href="{% url 'diary:diary_entry_create' %}">Создать запись</a>
      </button>
    </div>
  </div>

  {% for object in object_list %}
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-5 col-sm-4">
        {% if object.image %}
        <img src="{{ object.image|media_url }}" class="img-fluid w-100" alt="card-horizontal-image" />
        {% else %}
        <p>Изображения нет.</p>
        {% endif %}
      </div>
      <div class="col-7 col-sm-8">
        <div class="card-body">
          <a href="{% url 'diary:diary_entry_detail' object.pk %}" class="card-title"><h5>{{ object.title }}</h5></a>
          <p class="card-text">{{ object.text|truncatewords:50 }}</p>
          <p class="card-text">
            {% if user.is_superuser %}
            <small class="text-muted">Автор: {{ object.author.username }}</small><br />
            {% endif%}
            <small class="text-muted">Создано: {{ object.created_at }}</small><br />
            <small class="text-muted">В редакции от: {{ object.updated_at }}</small>
          </p>
        </div>
      </div>
    </div>
  </div>
  {% empty %}
  <p>Ничего не найдено.</p>
  {% endfor %}
</div>
{% endblock %}