apps/users/urls.py
from django.urls import path

from apps.users.apps import UsersConfig
from apps.users.views import (
    UserLoginView,
    UserLogoutView,
    UserRegisterView,
    ProfileView,
    UserPasswordResetView,
    email_verification,
    toggle_activity,
    ProfileUpdateView,
)

app_name = UsersConfig.name


urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/update/<int:pk>/", ProfileUpdateView.as_view(), name="update_profile"),
    path("confirm-email/<str:token>/", email_verification, name="confirm-email"),
    path("recovery/", UserPasswordResetView.as_view(), name="recovery"),
    path("toggle_activity/<int:pk>/", toggle_activity, name="toggle_activiti"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.diary.urls", namespace="diary")),
    path("users/", include("apps.users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


NULLABLE = {"null": True, "blank": True}


class Users(AbstractUser):

    email = models.EmailField(max_length=255, unique=True, verbose_name="Email")
    username = models.CharField(max_length=255, verbose_name="Никнейм пользователя")
    first_name = models.CharField(max_length=150, **NULLABLE, verbose_name="Имя пользователя")
    last_name = models.CharField(max_length=150, **NULLABLE, verbose_name="Фамилия пользователя")
    middle_name = models.CharField(max_length=150, **NULLABLE, verbose_name="Отчество пользователя")
    phone = models.CharField(max_length=50, **NULLABLE, verbose_name="Телефон")
    birthday = models.DateField(**NULLABLE, verbose_name="День рождения")
    avatar = models.ImageField(
        default="users/avatar/avatar_default.png", upload_to="users/avatar/", **NULLABLE, verbose_name="Аватарка"
    )

    token = models.CharField(max_length=120, **NULLABLE, verbose_name="Токен")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email} - {self.username}"

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        db_table = "_us_users"
        ordering = ["email"]
        unique_together = ["email", "username"]
        permissions = [
            ("set_user_deactivate", "Can deacticate Пользователь"),
            ("view_all_users", "Can view all Пользователь"),
        ]

apps/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm, PasswordResetForm
from django import forms
from core.forms import StyleFormMixin
from apps.users.models import Users


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = Users
        fields = ("email", "password1", "password2", "username")


class LoginForm(StyleFormMixin, AuthenticationForm):
    pass


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = Users
        fields = ("first_name", "last_name", "email", "phone", "avatar")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()


class RecoveryForm(StyleFormMixin, PasswordResetForm):
    pass

apps/users/views.py
import secrets

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from apps.users.forms import LoginForm, RecoveryForm, UserForm, UserRegisterForm
from apps.users.models import Users
from config.settings import EMAIL_HOST_USER
from core.services import make_random_password


class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = "users/login.html"
    success_url = reverse_lazy("users:profile")


class UserLogoutView(LogoutView):
    template_name = "users/login.html"


class UserRegisterView(CreateView):
    model = Users
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")
    extra_context = {"title": "Регистрация пользователя"}

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(15)
        user.token = token
        user.save()

        host = self.request.get_host()
        url = f"http://{host}/users/confirm-email/{token}/"

        try:
            send_mail(
                subject="Подтверждение электронной почты!",
                message=f"Здравствуйте! "
                f"Для подтверждения регистрации на сайте 'My Personal Diary' перейдите по ссылке:"
                f"{url}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
        except Exception:
            print("Ошибка при отправке письма верификации")
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(Users, token=token)
    user.is_active = True
    user.token = None
    user.save()
    return redirect(reverse("users:login"))


class UserPasswordResetView(PasswordResetView):
    form_class = RecoveryForm
    template_name = "users/recovery_form.html"

    def form_valid(self, form):
        if self.request.method == "POST":
            user_email = self.request.POST["email"]
            user = Users.objects.filter(email=user_email).first()
            if user:
                password = make_random_password()
                user.set_password(password)
                user.save()
                try:
                    send_mail(
                        subject="Восстановление пароля на сайте",
                        message=f"Здравствуйте!\n"
                        f"Ваш пароль для доступа на сайт 'My Personal Diary' изменен:\n"
                        f"Данные для входа:\n"
                        f"Email: {user_email}\n"
                        f"Пароль: {password}",
                        from_email=EMAIL_HOST_USER,
                        recipient_list=[user.email],
                    )
                except Exception as err:
                    print(err)
                    print(f"Ошибка при отправке пароля пользователю: ({user=}), на email: {user_email}")
            return HttpResponseRedirect(reverse("users:login"))
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, TemplateView):
    model = Users
    template_name = "users/profile.html"
    extra_context = {"title": "Профиль пользователя"}
    login_url = reverse_lazy("users:login")


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Users
    form_class = UserForm
    template_name = "users/user_form.html"
    extra_context = {"title": "Редактирование пользователя"}
    login_url = reverse_lazy("users:login")
    success_url = "users:profile"

    def get_object(self, *args, **kwargs):
        obj = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or user == obj:
            return obj
        else:
            raise PermissionDenied


@permission_required("users.set_user_deactivate")
def toggle_activity(request, pk):
    """Контроллер изменения статуса пользователя"""
    user = get_object_or_404(Users, pk=pk)
    user.is_active = not user.is_active
    user.save()
    return redirect(reverse("users:profile"))

apps/users/templates/users/login.html
{% extends 'diary/base.html' %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-3">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">Авторизация</h4>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success form-control">
                        Войти
                    </button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:recovery' %}" class="btn btn-outline-danger form-control">Восстановление пароля</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

apps/users/templates/users/profile.html
{% extends 'diary/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3 col-lg-2">
        <div class="list-group" id="list-tab" role="tablist">
            <a class="list-group-item list-group-item-action active" id="list-profile-list" data-bs-toggle="list"
               href="#list-profile" role="tab" aria-controls="home">Мой профиль</a>
            <a class="list-group-item list-group-item-action" id="list-statics-list" data-bs-toggle="list"
               href="#list-statistics" role="tab" aria-controls="profile">Моя статистика</a>
            {% if perms.users.view_all_users %}
            <a class="list-group-item list-group-item-action " id="list-users-list" data-bs-toggle="list"
               href="#list-users" role="tab" aria-controls="messages">Пользователи сервиса</a>
            {% endif %}
        </div>
        <div class="mt-3 text-center">
            {% if perms.users.change_users and user == user %}
            <button type="button" class="btn btn-outline-primary shadow-sm form-control">
                <a href="{% url 'users:update_profile' user.pk %}">Изменить</a>
            </button>
            {% endif %}
        </div>
    </div>
    <div class="col-9 col-lg-10">
        <div class="tab-content" id="list-nav-tabContent">
            <div class="tab-pane fade show active" id="list-profile" role="tabpanel"
                 aria-labelledby="list-profile-list">
                {% include 'users/profile_info.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/users/templates/users/profile_info.html
<div class="row">
    <div class="col-4">
        <div class="card">
            <img src="{{ user.avatar.url }}" class="card-img-top" alt="card-img-top">
        </div>
    </div>
    <div class="col-6">
        <div class="card-body">
            <h5 class="card-title">{{ user.first_name }} {{ user.last_name }} {{ user.middle_name }}</h5>
            <p class="card-text mt-1">Ваш никнейм: {{ user.username }}</p>
            <p class="card-text mt-1">Ваш email: {{ user.email }}</p>
            <p class="card-text mt-1">
                Телефон: {% if user.phone %} {{ user.phone }} {% else %} Не указано {% endif %}
            </p>
            <p class="card-text mt-1">
                Страна: {% if user.country %} {{ user.country }} {% else %} Не указано {% endif %}
            </p>
            <p class="card-text mt-1">
                Город: {% if user.city %} {{ user.city }} {% else %} Не указано {% endif %}
            </p>
            <p class="card-text mt-1">
                День рождения: {% if user.birthday %} {{ user.birthday }} {% else %} Не указано {% endif %}
            </p>
        </div>
    </div>
</div>

apps/users/templates/users/recovery_form.html
{% extends 'diary/base.html' %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-3">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">
                    Форма восстановления
                </h4>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-block btn-outline-success form-control">
                        Восстановить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

apps/users/templates/users/register.html
{% extends 'diary/base.html' %} {% block content %}

<div class="row justify-content-center">
  <div class="col-8">
    <div class="card">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal text-center">Регистрация</h4>
      </div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-outline-success form-control">
            Регистрация
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

apps/users/templates/users/user_form.html
{% extends 'diary/base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-xxl-3"></div>
    <div class="col-xxl-5">
      <p class="fs-4 text-center">Форма редактирования информации о пользователе {{ user.username }}</p>

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <button class="btn-outline-primary" type="submit">
          {% if object %} Изменить {% else %} Добавить {% endif %}
        </button>
        {% if object %}
        <button class="btn-outline-primary" type="button" onclick="window.location.href='{% url 'users:profile' %}'">
          Отмена
        </button>
        {% else %}
        <button class="btn-outline-primary" type="button" onclick="window.location.href='{% url 'users:profile' %}'">
          Отмена
        </button>
        {% endif %}
      </form>
    </div>
    <div class="col-xxl-4"></div>
  </div>
</div>
{% endblock %}