apps/diary/urls.py
from django.urls import path

from apps.diary.apps import DiaryConfig
from apps.diary.views import (
    HomeView,
    DiaryEntryListView,
    DiaryEntryDetailView,
    DiaryEntryCreateView,
    DiaryEntryDeleteView,
    DiaryEntryUpdateView,
)

app_name = DiaryConfig.name


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("diary/", DiaryEntryListView.as_view(), name="diary_entry_list"),
    path("diary/create/", DiaryEntryCreateView.as_view(), name="diary_entry_create"),
    path("diary/<int:pk>/", DiaryEntryDetailView.as_view(), name="diary_entry_detail"),
    path("diary/update/<int:pk>/", DiaryEntryUpdateView.as_view(), name="diary_entry_update"),
    path("diary/delete/<int:pk>/", DiaryEntryDeleteView.as_view(), name="diary_entry_delete"),
]

apps/users/urls.py
from django.urls import path

from apps.users.apps import UsersConfig
from apps.users.views import (
    UserLoginView,
    UserLogoutView,
    UserRegisterView,
    ProfileView,
    UserPasswordResetView,
    email_verification,
    toggle_activity,
    ProfileUpdateView,
)

app_name = UsersConfig.name


urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/update/<int:pk>/", ProfileUpdateView.as_view(), name="update_profile"),
    path("confirm-email/<str:token>/", email_verification, name="confirm-email"),
    path("recovery/", UserPasswordResetView.as_view(), name="recovery"),
    path("toggle_activity/<int:pk>/", toggle_activity, name="toggle_activiti"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.diary.urls", namespace="diary")),
    path("users/", include("apps.users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/diary/models.py
from django.db import models

from apps.users.models import NULLABLE, Users


class DiaryEntry(models.Model):
    """Модель записи пользователя в его дневнике."""

    author = models.ForeignKey(Users, on_delete=models.CASCADE, **NULLABLE, verbose_name="Автор")

    title = models.CharField(max_length=255, verbose_name="Название записи")
    text = models.TextField(verbose_name="Текст записи")
    image = models.ImageField(
        upload_to="diary/diary_entry", default="diary/diary_entry/default.png", **NULLABLE, verbose_name="Изображение"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    is_published = models.BooleanField(default=True, verbose_name="Статус публикации")

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"
        ordering = ["author", "updated_at"]
        db_table = "_d_diary_entry"
        db_table_comment = "Записи в дневнике"

apps/diary/forms.py
from django.forms import ModelForm
from core.forms import StyleFormMixin
from apps.diary.models import DiaryEntry


class DiaryEntryForm(StyleFormMixin, ModelForm):

    class Meta:
        model = DiaryEntry
        fields = ("title", "text", "image", "is_published")

apps/diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from apps.diary.forms import DiaryEntryForm
from apps.diary.models import DiaryEntry


class HomeView(TemplateView):
    template_name = "diary/home.html"
    extra_context = {"title": "Главная страница"}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return context_data


class DiaryEntryListView(ListView):
    model = DiaryEntry
    template_name = "diary/diary_entry/diary_entry_list.html"
    extra_context = {"title": "Мой дневник"}

    def get_queryset(self):
        queryset = super().get_queryset()

        user = self.request.user
        if user.is_superuser:
            return queryset
        else:
            queryset = queryset.filter(author=self.request.user)

            query = self.request.GET.get("q")
            if query:
                queryset = queryset.filter(Q(title__icontains=query) | Q(text__icontains=query))
            return queryset


class DiaryEntryDetailView(DetailView):
    model = DiaryEntry
    template_name = "diary/diary_entry/diary_entry_detail.html"
    extra_context = {"title": "Моя запись"}

    def get_object(self, *args, **kwargs):
        object = super().get_object()
        user = self.request.user
        if user.is_superuser or object.author == user:
            return object
        else:
            raise PermissionDenied


class DiaryEntryCreateView(LoginRequiredMixin, CreateView):
    model = DiaryEntry
    form_class = DiaryEntryForm
    template_name = "diary/diary_entry/diary_entry_form.html"
    extra_context = {"title": "Создать запис"}
    login_url = reverse_lazy("users:login")

    def get_success_url(self):
        return reverse("diary:diary_entry_detail", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class DiaryEntryUpdateView(LoginRequiredMixin, UpdateView):
    model = DiaryEntry
    form_class = DiaryEntryForm
    template_name = "diary/diary_entry/diary_entry_form.html"
    extra_context = {"title": "Редактировать запись"}
    login_url = reverse_lazy("users:login")

    def get_success_url(self):
        return reverse("diary:diary_entry_detail", kwargs={"pk": self.object.pk})

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or object.author == user:
            return object
        else:
            raise PermissionDenied


class DiaryEntryDeleteView(LoginRequiredMixin, DeleteView):
    model = DiaryEntry
    template_name = "diary/diary_entry/diary_entry_form.html"
    extra_context = {"title": "Удаление статьи"}
    success_url = reverse_lazy("diary:diary_entry_list")
    login_url = reverse_lazy("users:login")

    def get_object(self, *args, **kwargs):
        object = super().get_object()
        user = self.request.user
        if user.is_superuser or object.author == user:
            return object
        else:
            raise PermissionDenied

apps/diary/templates/diary/subtemplates/header.html
<nav class="navbar navbar-expand-md" aria-label="Fourth navbar example">
  <div class="container-xl">
  <a class="navbar-brand me-5" href="{% url 'diary:home' %}"><h1 class="display-4 m-0">Your Space for Thoughts</h1></a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" 
    aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon">
      
    </span></button>

    {% if user.is_authenticated %}

    <div class="collapse navbar-collapse align-content-between flex-wrap gap-2" id="navbarsExample04">
      <div class="navbar-nav gap-2 ms-md-auto mb-4 mb-sm-1 mb-md-0">
        <a class="btn btn-outline-dark shadow-sm" href=" {% url 'diary:diary_entry_list' %}">Мой дневник</a>
        <a class="btn btn-outline-dark shadow-sm" href=" {% url 'diary:diary_entry_create' %}">Создать запись</a>
        <a class="p-2 btn btn-warning mr-1" href="{% url 'users:profile' %}">{{ user.email }}</a>

      </div>
      <div class="navbar-nav ms-md-auto gap-2">
        <a>
          <form action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="p-2 btn btn-danger">Выйти</button>
          </form>
        </a>

        {% else %}
        <div class="navbar-nav gap-2 ms-md-auto mb-4 mb-sm-1 mb-md-0"> 
          <button class="btn btn-outline-primary" type="submit"><a href="{% url 'users:login' %}">Войти</a></button>
          <button class="btn btn-outline-success" type="submit"><a href="{% url 'users:register' %}">Зарегистрироваться</a></button>
        </div>
      </div>
    {% endif %}
  </div>
</nav>